name: 'Terraform Azure CI/CD' 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0-alpha20250213

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      # - name: Terraform Import Existing Resources
      #   run: |
      #     terraform import azurerm_resource_group.tf-az-rg /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources || echo "Resource Group already imported"
      #     terraform import azurerm_virtual_network.tf-az-vnet /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Network/virtualNetworks/tf-az-network || echo "VNet already imported"
      #     terraform import azurerm_subnet.tf-az-subnet /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Network/virtualNetworks/tf-az-network/subnets/tf-az-subnet || echo "Subnet already imported"
      #     terraform import azurerm_network_security_group.tf-az-nsg /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Network/networkSecurityGroups/tf-az-nsg || echo "NSG already imported"
      #     terraform import azurerm_network_security_rule.tf-az-nsg-rule /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Network/networkSecurityGroups/tf-az-nsg/securityRules/tf-az-nsg-rule || echo "NSG Rule already imported"
      #     terraform import azurerm_public_ip.tf-az-pip /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Network/publicIPAddresses/tf-az-pip || echo "Public IP already imported"
      #     terraform import azurerm_subnet_network_security_group_association.tf-az-subnet-nsg /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Network/virtualNetworks/tf-az-network/subnets/tf-az-subnet || echo "Subnet NSG Association already imported"
      #     terraform import azurerm_network_interface.tf-az-nic /subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Network/networkInterfaces/tf-az-nic || echo "Network Interface already imported"
      #     terraform import azurerm_linux_virtual_machine.ta-az-vm "/subscriptions/256c47d7-6c5f-4e92-b116-d234771e3690/resourceGroups/tf-az-resources/providers/Microsoft.Compute/virtualMachines/ta-az-vm" || echo "Already imported"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

        
