name: 'Terraform Azure CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-apply:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0-alpha20250213

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Backend Storage Account
        run: |
          az group create --name tf-az-backend-rg --location eastus
          az storage account create --name tfazbackend123 --resource-group tf-az-backend-rg --sku Standard_LRS --kind StorageV2 --allow-blob-public-access false
          az storage container create --name tfstate --account-name tfazbackend123

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform-apply # Runs only after apply is successful

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0-alpha20250213

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Wait Before Destroy
        run: sleep 30  # Wait 60 seconds before destroying

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Delete Backend Storage
        run: |
          az storage account delete --name tfazbackend123 --resource-group tf-az-backend-rg --yes
          az group delete --name tf-az-backend-rg --yes --no-wait